name: basic-workflow
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test > test.log
      - name: Archive build's test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test_log
          path: test-app/test.log
    
  workflow-restart:
    if: ${{ failure() }} # ${{ run-tests.status == 'failure' }}
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Downloading build's test log
        uses: actions/download-artifact@v3
        with:
          name: test_log
      - name: Outputing log
        run: cat test.log